apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentwins-fmi-api-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: opentwins-fmi-api
  name: opentwins-fmi-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod-opentwins-fmi-api
  template:
    metadata:
      labels:
        name: pod-opentwins-fmi-api
      name: opentwins-fmi-api
    spec:
      serviceAccountName: ot-fmi
      automountServiceAccountToken: true
      volumes:
        - name: opentwins-fmi-api-data
          persistentVolumeClaim:
            claimName: opentwins-fmi-api-data
      containers:
        - image: docker.ertis.uma.es/fmi-release/opentwins-fmi-simulator-api-v2:latest
          name: opentwins-fmi-api
          env:
          - name: SQLITE_DB_PATH
            value: /usr/src/app/data/fmi_schemas.db
          # - name: KUBE_NAMESPACE
          #   value:
          # - name: INSIDE_CLUSTER
          #   value:
          # - name: INFLUXDB_HOST
          #   value:
          # - name: INFLUXDB_TOKEN
          #   value:
          # - name: INFLUXDB_DB
          #   value:
          # - name: MINIO_TOKEN
          #   value:
          # - name: MINIO_URL
          #   value:
          # - name: MINIO_A_KEY
          #   value:
          # - name: MINIO_S_KEY
          #   value:
          # - name: BROKER_TYPE
          #   value:
          # - name: BROKER_IP
          #   value:
          # - name: BROKER_PORT
          #   value:
          # - name: BROKER_TOPIC
          #   value:
          # - name: BROKER_USERNAME
          #   value:
          # - name: BROKER_PASSWORD
          #   value:
          volumeMounts:
            - name: opentwins-fmi-api-data
              mountPath: /usr/src/app/data
          ports:
            - containerPort: 8001
          imagePullPolicy: Always