apiVersion: v1
kind: ServiceAccount
metadata:
  name: ot-fmi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ot-fmi-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ot-fmi-role-binding
subjects:
  - kind: ServiceAccount
    name: ot-fmi
roleRef:
  kind: Role
  name: ot-fmi-role
  apiGroup: rbac.authorization.k8s.io
