apiVersion: v1
kind: Service
metadata:
  name: opentwins-fmi-api
spec:
  selector:
    name: pod-opentwins-fmi-api
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 8000
    nodePort: 30480
    targetPort: 8000